[package]
name = "moq-pub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
moq-transport-quinn = { version = "0.1.0", path = "../moq-transport-quinn" }
moq-warp = { version = "0.1.0", path = "../moq-warp" }
webtransport-quinn = "0.4.2"
