[package]
name = "moq-warp"
description = "Media over QUIC"
authors = [ "Luke Curley" ]
repository = "https://github.com/kixelated/moq-rs"
license = "Apache-2.0"

version = "0.1.0"
edition = "2021"

keywords = [ "quic", "http3", "webtransport", "media", "live" ]
categories = [ "multimedia", "network-programming", "web-programming" ]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
moq-transport = { path = "../moq-transport" }

# Async stuff
tokio = { version = "1.27", features = ["full"] }
futures = "0.3"

# Media
mp4 = "0.13.0"

# Encoding
bytes = "1"

# Utility
anyhow = "1.0.70"
thiserror = "1.0.21"
async-trait = "0.1"
