[package]
name = "moq-relay"
description = "Media over QUIC"
authors = ["Luke Curley"]
repository = "https://github.com/kixelated/moq-rs"
license = "MIT OR Apache-2.0"

version = "0.1.0"
edition = "2021"

keywords = ["quic", "http3", "webtransport", "media", "live"]
categories = ["multimedia", "network-programming", "web-programming"]

[dependencies]
moq-transport = { path = "../moq-transport" }
moq-api = { path = "../moq-api" }

# QUIC
quinn = "0.10"
webtransport-generic = "0.5"
webtransport-quinn = "0.5"
http = "0.2"
url = "2.4"

# Crypto
ring = "0.16.20"
rustls = "0.21.2"
rustls-pemfile = "1.0.2"
rustls-native-certs = "0.6.3"

# Async stuff
tokio = { version = "1", features = ["full"] }

# Web server to serve the fingerprint
warp = { version = "0.3.3", features = ["tls"] }
hex = "0.4.3"

# Error handling
anyhow = "1.0.70"
thiserror = "1"

# CLI
clap = { version = "4.0", features = ["derive"] }

# Logging
log = { version = "0.4", features = ["std"] }
env_logger = "0.9.3"
tracing = "0.1"
tracing-subscriber = "0.3.0"
