[package]
name = "moq-relay"
description = "Media over QUIC"
authors = ["Luke Curley"]
repository = "https://github.com/kixelated/moq-rs"
license = "MIT OR Apache-2.0"

version = "0.1.0"
edition = "2021"

keywords = ["quic", "http3", "webtransport", "media", "live"]
categories = ["multimedia", "network-programming", "web-programming"]

[dependencies]
moq-transport = { path = "../moq-transport" }
moq-api = { path = "../moq-api" }

# QUIC
quinn = "0.10"
webtransport-quinn = "0.6"
#webtransport-quinn = { path = "../../webtransport-rs/webtransport-quinn" }
url = "2"

# Crypto
ring = "0.16"
rustls = "0.21"
rustls-pemfile = "1"
rustls-native-certs = "0.6"

# Async stuff
tokio = { version = "1", features = ["full"] }

# Web server to serve the fingerprint
warp = { version = "0.3.6", features = ["tls"] }
hex = "0.4"

# Error handling
anyhow = { version = "1", features = ["backtrace"] }
thiserror = "1"

# CLI
clap = { version = "4", features = ["derive"] }

# Logging
log = { version = "0.4", features = ["std"] }
env_logger = "0.9"
tracing = "0.1"
