name: web

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web

    steps:
    - uses: actions/checkout@v3

    - name: install
      run: yarn install

    - name: cert
      working-directory: cert
      run: ./generate

    - name: build
      run: yarn build

    - name: lint
      run: yarn lint
